'''DUNDER VARIABLES

-> Short form for Double Underscore.
-> Dunder variables are predefined special variables with double underscores at the start and end.
-> These variables are automatically created by Python. 
-> They help in identifying modules.
-> Track where the file is stored.
-> Control how the module behaves when they are imported.
-> For providing documentation.

Dunder Variables:
1. __name__
2. __file__
3. __cached__
4. __package__
5. __doc__


1. __name__

-> It represents the name of the module.
-> If the Python module/file is executed directly, then this variable will be assigned with the value "__main__".

Note:
If the module having the __name__ variable is executed because of importing, then that module name will be assigned as the value to __name__.

Purpose:
To prevent/avoid certain code from getting executed, we use a conditional block.

Syntax:

if __name__ == "__main__":
    # Only testing code should get executed

Example:

print(__name__)

Output:
__main__      -> when the file is executed directly.
<<<<<<< HEAD:dunder_variables/dunder_var.py
module name   -> when the file is executed because of importing.'''
=======
module name   -> when the file is executed because of importing.

2. __file__

-> this dunder variable provides or shows full file path of the currently executing file.

3. __cached__

-> this shows the full file path of the bytecode cached file (.pyc) generated by the module

4. __package__

-> this shows or gives the package name in which the module is executed

5. __doc__

-> it stores the docstring of a module / function / class / method

-> docstring is written at the very beginning of a module or a class / func / method 



'''
>>>>>>> 988c992 (add oops and package architecture):package_architecture/dunder_variables/dunder_var.py
